
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ipedrazas.kubernetes-snippets
tasks:
  - name: Login with Okteto
    before: ./run okteto-login || true
    command: exit 0