
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ipedrazas.kubernetes-snippets
tasks:
  - name: Init scripts
    init: direnv allow
    before: |
      direnv allow
      direnv reload
      ./run okteto-login || true
    command: exit 0